project_id = "ayhwkwdshvpmxbooyiom"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.make-server-012a3b25]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.verify-dossier]
    verify_jwt = false
