/* AUTOGENERATED FILE - apunta a Lovable Cloud */

export const projectId = import.meta.env.VITE_SUPABASE_PROJECT_ID as string;
export const publicAnonKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string;
