/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "bdphuxspjodtljfiwfkg"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJkcGh1eHNwam9kdGxqZml3ZmtnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI4MDI3NDUsImV4cCI6MjA3ODM3ODc0NX0.le-6ltX_FL-Aif3NReTyt183WgrK3n9yyfiDHXnF7lI"